### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by thehydroimpulse** [deric92/WebSocketApp#1]
/cc @deric92 

1. Use environment variables instead of hard coding them into your code.

```bash
# ~/.bash_profile (or ~/.bashrc or ~/.zshrc)
export DB_HOST="..."
export DB_USER="..."
export DB_PASS="..."
export DB="..."
```

Then use it in your code:

```js
const dbConfig = {
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  pass: process.env.DB_PASS,
  db: process.env.DB
};
```

Now that your credentials have been leaked publicly, you'll want to change the username and password in AWS asap. Assume that someone has gotten their hands on those credentials (lots of bots scan github for this kind of stuff).

2. Indent, indent, indent.

This will probably improve the readability of your code by 100x. Indent by 2 spaces and keep the nesting consistent. Use auto indent tools to help you.

3. Never have more than one empty line sequentially.

e.g.,

Bad:

```js

var foobar = 123;


function done() {}
```

Good:

```js
var foobar = 123;

function done() {}
```

3. Remove useless comments.

Comments like `// START HERE` or `// CONFIG` are bad and don't do anything to improve readability. Never comment about the *what*, comment about the *why*.

4. Don't use `var` anymore. It's going to cause you a lot of pain because it's not lexically scoped.

If the variable doesn't change, use `const`.

```js
// bad
var fs = require('fs');
// good
const fs = require('fs');
```

If the variable needs to change, use `let`.

```js
// bad
var a = 2;
a = 3;
// good
let a = 2;
a = 3;
```

Let has lexical scoping.

```js
// wrong
for (var i = 0; i < 5; i++) {
   // ...
}

console.log(i);

// good
for (let i = 0; i < 5; i++) {

}

console.log(i);
```

Try this out and you'll see they don't do the same thing. `let` semantics is what you want.

5. Use strict mode

To use `let`, you'll need to enable strict mode, which is recommended anyways.

```js
'use strict';

let a = 2;
a = 3;
```

At the top of every file, put `'use strict';`

Most of this is about learning on the way. Javascript has a lot of bad parts to it, so it's hard to only learn the good ones.

**Comment by deric92** [comment]
## Thanks for the feedback!

Wow thanks for taking the time to write this out, I really appreciate it! 

Got the Env. variables set up, and I nuked the database and started over just to make sure. New user, new password, new endpoint completely.

## I'm totally ashamed of my indenting... 

I seem to always let it go to shit. I really have to work on that. 

I'll implement the use of `const` instead of `var` whenever an object doesn't change
And I'll implement the use of `let` wherever an object has to change and I'll make sure to use `strict` mode everywhere.

**Comment by deric92** [comment]
Also I changed my database to use PostgreSQL.

**Comment by thehydroimpulse** [comment]
Here's a codified style guide you should follow: https://github.com/airbnb/javascript

**Comment by deric92** [comment]
> Here's a codified style guide you should follow: https://github.com/airbnb/javascript

I'll definitely slowly introduce those habits into my code over time.  Going to be a challenge but so worth it over time.
